import type { Producer, Product } from '../types'

export const PRODUCERS: Producer[] = [
  {
    id: 'p1', name: 'Agave Azul del Highlands', state: 'Jalisco', category: 'bebidas',
    description: 'Productor de tequila premium con 45 años de tradición en los Altos de Jalisco. Exportamos a 12 países europeos.',
    verified: true, founded: 1979, employees: '50-100',
    certifications: ['denominacion-origen', 'nom', 'senasica'],
    exportCountries: ['DE', 'NL', 'FR', 'BE', 'ES'],
    logo: '🌵', rating: 4.9, totalProducts: 8,
  },
  {
    id: 'p2', name: 'Valles Orgánicos de Oaxaca', state: 'Oaxaca', category: 'agricultura',
    description: 'Cooperativa de 120 familias productoras de mezcal artesanal y productos agrícolas orgánicos certificados.',
    verified: true, founded: 2003, employees: '100-200',
    certifications: ['organico', 'denominacion-origen', 'kosher-halal'],
    exportCountries: ['NL', 'DE', 'IT', 'SE'],
    logo: '🫙', rating: 4.8, totalProducts: 12,
  },
  {
    id: 'p3', name: 'Selva Maya Bee Co.', state: 'Yucatán', category: 'agricultura',
    description: 'Productores de miel melipona y miel silvestre con certificación orgánica y comercio justo.',
    verified: true, founded: 2010, employees: '10-50',
    certifications: ['organico', 'cofepris'],
    exportCountries: ['DE', 'FR', 'ES', 'PL'],
    logo: '🐝', rating: 4.7, totalProducts: 5,
  },
  {
    id: 'p4', name: 'Café Sierra Madre', state: 'Chiapas', category: 'agricultura',
    description: 'Café de especialidad de altura, cultivado a 1,800 msnm. Varietales Bourbon, Catuaí y Maragogipe.',
    verified: true, founded: 1998, employees: '50-100',
    certifications: ['organico', 'senasica', 'kosher-halal'],
    exportCountries: ['NL', 'DE', 'SE', 'FI', 'DK'],
    logo: '☕', rating: 4.9, totalProducts: 7,
  },
  {
    id: 'p5', name: 'Jojoba del Desierto Sonorense', state: 'Sonora', category: 'cosmeticos',
    description: 'Extracción y refinado de aceite de jojoba prensado en frío para industria cosmética y farmacéutica.',
    verified: true, founded: 2005, employees: '10-50',
    certifications: ['cofepris', 'organico', 'nom'],
    exportCountries: ['DE', 'FR', 'NL', 'IT', 'AT'],
    logo: '🌿', rating: 4.6, totalProducts: 4,
  },
  {
    id: 'p6', name: 'Textiles Artesanales Teotitlán', state: 'Oaxaca', category: 'artesanias',
    description: 'Tapetes y textiles zapotecas elaborados con tintes naturales. 400 años de tradición familiar.',
    verified: true, founded: 2001, employees: '10-50',
    certifications: ['nom'],
    exportCountries: ['ES', 'FR', 'DE', 'NL'],
    logo: '🧵', rating: 4.8, totalProducts: 15,
  },
  {
    id: 'p7', name: 'Herbolaria Michoacana', state: 'Michoacán', category: 'farmaceutico',
    description: 'Procesamiento y exportación de plantas medicinales, extractos y suplementos herbolarios con COFEPRIS.',
    verified: true, founded: 2012, employees: '10-50',
    certifications: ['cofepris', 'nom', 'senasica'],
    exportCountries: ['DE', 'NL', 'ES'],
    logo: '🌱', rating: 4.5, totalProducts: 22,
  },
  {
    id: 'p8', name: 'Chiles & Especias de Puebla', state: 'Puebla', category: 'agricultura',
    description: 'Deshidratado y empaque de chiles mexicanos: ancho, mulato, pasilla, chipotle y mole negro.',
    verified: false, founded: 2015, employees: '10-50',
    certifications: ['senasica', 'nom'],
    exportCountries: ['ES', 'FR'],
    logo: '🌶️', rating: 4.3, totalProducts: 9,
  },
]

export const PRODUCTS: Product[] = [
  {
    id: 'prod1', name: 'Tequila Añejo Reserva', nameEn: 'Reserva Añejo Tequila',
    category: 'bebidas', producerId: 'p1', producerName: 'Agave Azul del Highlands',
    state: 'Jalisco', price: 48.50, currency: 'USD', unit: 'botella', unitEn: 'bottle',
    moq: 200, moqUnit: 'cajas', certifications: ['denominacion-origen', 'nom'],
    verified: true, icon: '🥃',
    description: 'Tequila 100% agave azul, añejado 18 meses en barricas de roble americano.',
    descriptionEn: '100% blue agave tequila, aged 18 months in American oak barrels.',
    inStock: true, trending: true,
  },
  {
    id: 'prod2', name: 'Arándanos Orgánicos Frescos', nameEn: 'Fresh Organic Blueberries',
    category: 'agricultura', producerId: 'p2', producerName: 'Valles Orgánicos de Oaxaca',
    state: 'Oaxaca', price: 3.20, currency: 'USD', unit: 'kg', unitEn: 'kg',
    moq: 500, moqUnit: 'kg', certifications: ['organico', 'senasica'],
    verified: true, icon: '🫐',
    description: 'Arándanos cultivados en los valles de Oaxaca, sin agroquímicos.',
    descriptionEn: 'Blueberries grown in Oaxaca valleys, without agrochemicals.',
    inStock: true,
  },
  {
    id: 'prod3', name: 'Café Chiapaneco de Altura', nameEn: 'Chiapas Highland Coffee',
    category: 'agricultura', producerId: 'p4', producerName: 'Café Sierra Madre',
    state: 'Chiapas', price: 12.80, currency: 'USD', unit: 'kg', unitEn: 'kg',
    moq: 250, moqUnit: 'kg', certifications: ['organico', 'senasica'],
    verified: true, icon: '☕',
    description: 'Café de especialidad SHB, notas a chocolate amargo, nuez y caramelo.',
    descriptionEn: 'Specialty SHB coffee, notes of dark chocolate, walnut and caramel.',
    inStock: true, trending: true,
  },
  {
    id: 'prod4', name: 'Aceite de Jojoba Prensado en Frío', nameEn: 'Cold-Pressed Jojoba Oil',
    category: 'cosmeticos', producerId: 'p5', producerName: 'Jojoba del Desierto Sonorense',
    state: 'Sonora', price: 22.00, currency: 'USD', unit: 'litro', unitEn: 'liter',
    moq: 100, moqUnit: 'L', certifications: ['organico', 'cofepris'],
    verified: true, icon: '🌿',
    description: 'Aceite refinado, grado cosmético, libre de hexano. Índice de yodo: 80-85.',
    descriptionEn: 'Refined oil, cosmetic grade, hexane-free. Iodine index: 80-85.',
    inStock: true,
  },
  {
    id: 'prod5', name: 'Miel Melipona Maya', nameEn: 'Melipona Maya Honey',
    category: 'agricultura', producerId: 'p3', producerName: 'Selva Maya Bee Co.',
    state: 'Yucatán', price: 35.00, currency: 'USD', unit: 'kg', unitEn: 'kg',
    moq: 50, moqUnit: 'kg', certifications: ['organico', 'cofepris'],
    verified: true, icon: '🍯',
    description: 'Miel de abeja melipona, sin aguijón. Propiedades medicinales reconocidas por UNAM.',
    descriptionEn: 'Stingless melipona bee honey. Medicinal properties recognized by UNAM.',
    inStock: true, newProduct: true,
  },
  {
    id: 'prod6', name: 'Chile Ancho Deshidratado', nameEn: 'Dried Ancho Chili',
    category: 'agricultura', producerId: 'p8', producerName: 'Chiles & Especias de Puebla',
    state: 'Puebla', price: 8.50, currency: 'USD', unit: 'kg', unitEn: 'kg',
    moq: 300, moqUnit: 'kg', certifications: ['senasica', 'nom'],
    verified: false, icon: '🌶️',
    description: 'Chile ancho (poblano maduro seco), color rojo intenso, sin semillas.',
    descriptionEn: 'Ancho chili (dried ripe poblano), deep red color, seedless.',
    inStock: true,
  },
  {
    id: 'prod7', name: 'Mezcal Artesanal Espadín', nameEn: 'Artisanal Espadín Mezcal',
    category: 'bebidas', producerId: 'p2', producerName: 'Valles Orgánicos de Oaxaca',
    state: 'Oaxaca', price: 62.00, currency: 'USD', unit: 'botella', unitEn: 'bottle',
    moq: 120, moqUnit: 'cajas', certifications: ['denominacion-origen', 'nom'],
    verified: true, icon: '🫙',
    description: 'Mezcal artesanal de agave espadín, destilado en olla de barro. 46% alc.',
    descriptionEn: 'Artisanal espadín agave mezcal, distilled in clay pot. 46% alc.',
    inStock: true, trending: true,
  },
  {
    id: 'prod8', name: 'Tapete Zapoteca Lana Natural', nameEn: 'Natural Wool Zapotec Rug',
    category: 'artesanias', producerId: 'p6', producerName: 'Textiles Artesanales Teotitlán',
    state: 'Oaxaca', price: 185.00, currency: 'USD', unit: 'pieza', unitEn: 'piece',
    moq: 20, moqUnit: 'piezas', certifications: ['nom'],
    verified: true, icon: '🧵',
    description: 'Tapete 150×90 cm, lana de borrego, tintes naturales (añil, cochinilla, corteza).',
    descriptionEn: '150×90 cm rug, sheep wool, natural dyes (indigo, cochineal, bark).',
    inStock: true, newProduct: true,
  },
  {
    id: 'prod9', name: 'Extracto de Sábila Orgánica', nameEn: 'Organic Aloe Vera Extract',
    category: 'cosmeticos', producerId: 'p7', producerName: 'Herbolaria Michoacana',
    state: 'Michoacán', price: 4.80, currency: 'USD', unit: 'litro', unitEn: 'liter',
    moq: 200, moqUnit: 'L', certifications: ['cofepris', 'organico'],
    verified: true, icon: '🌱',
    description: 'Gel de aloe vera 99.7% puro, estabilizado, grado cosmético y alimentario.',
    descriptionEn: '99.7% pure aloe vera gel, stabilized, cosmetic and food grade.',
    inStock: true,
  },
  {
    id: 'prod10', name: 'Café Verde Lavado', nameEn: 'Washed Green Coffee',
    category: 'agricultura', producerId: 'p4', producerName: 'Café Sierra Madre',
    state: 'Chiapas', price: 7.90, currency: 'USD', unit: 'kg', unitEn: 'kg',
    moq: 500, moqUnit: 'kg', certifications: ['organico', 'senasica'],
    verified: true, icon: '☕',
    description: 'Café verde sin tostar, proceso lavado, humedad 11%. Certificado de exportación SENASICA.',
    descriptionEn: 'Unroasted green coffee, washed process, 11% humidity. SENASICA export certificate.',
    inStock: true,
  },
  {
    id: 'prod11', name: 'Tequila Blanco Premium', nameEn: 'Premium Blanco Tequila',
    category: 'bebidas', producerId: 'p1', producerName: 'Agave Azul del Highlands',
    state: 'Jalisco', price: 32.00, currency: 'USD', unit: 'botella', unitEn: 'bottle',
    moq: 300, moqUnit: 'cajas', certifications: ['denominacion-origen', 'nom'],
    verified: true, icon: '🥃',
    description: 'Tequila blanco 100% agave, reposado 45 días. Notas de agave, pimiento y cítrico.',
    descriptionEn: '100% agave blanco tequila, 45-day rest. Notes of agave, pepper and citrus.',
    inStock: true,
  },
  {
    id: 'prod12', name: 'Polvo de Chile Chipotle', nameEn: 'Chipotle Chili Powder',
    category: 'agricultura', producerId: 'p8', producerName: 'Chiles & Especias de Puebla',
    state: 'Puebla', price: 11.20, currency: 'USD', unit: 'kg', unitEn: 'kg',
    moq: 200, moqUnit: 'kg', certifications: ['senasica'],
    verified: false, icon: '🌶️',
    description: 'Chipotle ahumado molido, scoville 5,000-10,000 UHS. Empaque hermético exportación.',
    descriptionEn: 'Ground smoked chipotle, 5,000-10,000 SHU. Export hermetic packaging.',
    inStock: false,
  },
]
